// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("count")
	ScopeName = "github.com/carsonip/otel-tbs-playground/exporter/countexporter"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
